version: '3.4'
services:
  sentiment-analysis-share-share:
    image: alfresco-share-sentiment-analysis-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
      REPO_HOST: sentiment-analysis-share-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  sentiment-analysis-share-acs:
    image: ${docker.acs.image}:${alfresco.platform.version}
    environment:
      JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://sentiment-analysis-share-postgres:5432/alfresco
                -Dsolr.host=sentiment-analysis-share-ass
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dcsrf.filter.enabled=false
                "
    ports:
      - "${acs.port}:8080"
    volumes:
      - sentiment-analysis-share-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - sentiment-analysis-share-postgres
  sentiment-analysis-share-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - "${postgres.port}:5432"
    volumes:
      - sentiment-analysis-share-db-volume:/var/lib/postgresql/data
  sentiment-analysis-share-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: sentiment-analysis-share-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: sentiment-analysis-share-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - sentiment-analysis-share-ass-volume:/opt/alfresco-search-services/contentstore
      - sentiment-analysis-share-ass-volume:/opt/alfresco-search-services/data
volumes:
  sentiment-analysis-share-acs-volume:
    external: true
  sentiment-analysis-share-db-volume:
    external: true
  sentiment-analysis-share-ass-volume:
    external: true